### ISSUE TITLE
Chọn chủ đề

### ISSUE THREAD

**Issue by quangster** [96ers/Eng-to-Vie-Summarizer#1]
@quangster @XuanNguyen-UET @chirikatori @CoderHung
Gợi ý:
1. Clone 1 tool trên [almanack](https://www.almanack.ai/tools)
2. Có thể phát triển tiếp các dự án mã nguồn mở: [langchain](https://github.com/kyrolabs/awesome-langchain), ...
3. Clone phần mềm hot, phát triển các tính năng premium của phần mềm đó
4. Thảo luận, tìm một ý tưởng khác

**Comment by chirikatori** [comment]
@quangster @XuanNguyen-UET @CoderHung  @chirikatori 
giờ theo t ấy thì mọi người cứ dành ra khoảng 2 tuần để tìm hiểu cả 4 phương pháp đi, xong sau đó mọi người cùng ngồi lại với nhau bàn xong phân công công việc với cả bắt đầu làm luôn

**Comment by chirikatori** [comment]
tại vì cái hôm ngồi với nhau là ae mình ko chỉ bàn mỗi về phương pháp mà còn bàn cả về format code, git branch, framework, v.v...

**Comment by XuanNguyen-UET** [comment]
Ý tưởng: 
- Công cụ summanirizer bao gồm:
+ đầu vào:-  văn bản
	  -  (có thể mở rộng đầu vào...)
+ đầu ra: 
	- văn bản đã được: 
		+ tóm tắt 
		+ (optional) dịch sang tiếng Việt

Ngôn ngữ: 
	- Python, JavaScript
	- Framework: Tính sau (React, ...)
	- DataBase:MySQL 
	- 
Use Case: 
	- Chọn loại đầu vào 
		+ Generator
	- Chọn số câu để tóm tắt
	- Create
	- Dịch
Document: 
	_ google docs
	_

**Comment by XuanNguyen-UET** [comment]
Chỉnh lại tên Project: từ Eng-to-Vie-summerizer -> Eng-to-Vie-Summarizer
